### ISSUE TITLE
Upgrade to Alamofire 5

### ISSUE THREAD

**Issue by gyulavoros** [idnow/de.idnow.ios.sdk#12]
Alamofire 5 is available as of Feb 15. Currently, we are using Alamofire 4 in our app as well but eventually, we would like to migrate to version 5 because we need a couple of new features. Are there any plans for the IDNow SDK to upgrade?

Transitive dependencies are always an interesting topic, depending on how much work would it take on your side, but relying on `URLSession` only inside the SDK is another option, so client apps are free to choose their own dependencies.

**Comment by BilelSelmiIDnow** [comment]
@gyulavoros : At the moment we are still using Alamofire 4 but there are plans to upgrade to Alamofire 5.
Thanks

**Comment by tjanela** [comment]
We are also using Alamofire 5 in our application and we need this done. Downgrading to Alamofire 4 is not an option we are considering.
@BilelSelmiIDnow:
What are the plans? 
Is there a timeline for this? 
Do you need help?

**Comment by BilelSelmiIDnow** [comment]
@tjanela : we are replacing Alamofire with URLSession in the next release, it should be some time next week. Then you can use Alamofire 5 with no issues

**Comment by tjanela** [comment]
@BilelSelmiIDnow, that is actually a much better approach from my point of view. Thanks!

**Comment by gyulavoros** [comment]
It was the right call, thanks for making this happen. 🙌

**Comment by joselinoneto** [comment]
any progress? related to this new release without alamofire?

**Comment by tjanela** [comment]
We were told we would be having a release last week. What is the status @BilelSelmiIDnow? Our client (and most importantly our users) is (are) waiting on this...

**Comment by lukasz-lenkiewicz** [comment]
im also looking for this change, any update here?

**Comment by BilelSelmiIDnow** [comment]
The release is ready now, we replaced Alamofire with URLsession.
Thank you for your patience.
