### ISSUE TITLE
Not running in simulator

### ISSUE THREAD

**Issue by girishsami** [idnow/de.idnow.ios.sdk#13]
Recently I have updated idnow sdk to **IDnow-platform-iOS-Xcode_11.4.1** , after updated idnow sdk my app is not running in simulator, but working fine in Device, when selected Simulator getting below error.

**Could not find module 'IDNowSDKCore' for target 'x86_64-apple-ios-simulator'; found: arm64, armv7-apple-ios, arm64-apple-ios, arm, armv7**

Please suggest to resolve this issue.

**Comment by BilelSelmiIDnow** [comment]
@girishsami : for Cocoapods installation The framework itself contains `armv7` and `arm64` architectures but not simulator architectures, if the simulator architectures are needed we can provide you with a universal framework, but for uploading to App Store you have to strip the simulator architectures using a script.

For Carthage : we are already providing a universal framework.

**Comment by IvanFomenkoAndersenLab** [comment]
@BilelSelmiIDnow Hello! How I can get a universal framework for testing on Simulator?
