### ISSUE TITLE
Dependency on Sentry

### ISSUE THREAD

**Issue by gyulavoros** [idnow/de.idnow.ios.sdk#14]
We are using Firebase Crashlytics in our application for crash reporting. We recently realized that having multiple crash reporting tools might interfere with each other. The IDNow iOS SDK has a hard dependency on Sentry, which may be problematic for a couple of reasons:
- it is possible, that we are not receiving crash reports because sentry is catching them and forwards them to you
- handling of user data and GDPR compliance might be not fully transparent
- our application's bundle size gets bigger for something that we are not benefiting from

I didn't find much information on this regard except [this forum conversation](https://forum.sentry.io/t/ios-use-sentry-and-fabric-at-the-same-time/590/10). Some folks are claiming it should work, others reported:
> It’s randomly send crashes to Fabric or Sentry.

Also, I've checked the IDNow Android SDK and that one doesn't seem to rely on Sentry. Would it be possible to get rid of the Sentry for the iOS SDK as well?

**Comment by BilelSelmiIDnow** [comment]
@gyulavoros : We are currently working on this topic, we are considering removing Sentry dependency thanks
