### ISSUE TITLE
Plugin crashes on older iOS versions

### ISSUE THREAD

**Issue by timohe** [idnow/de.idnow.ios.sdk#15]
We have some iOS users which complain that our app crashes on startup. 
We were able to pinpoint this issue to this plugin by removing it. Also the issue started just when we rolled out autoident (Version 3.21.0).

This is the error we see when running locally on a iOS 10.3.2 device:
```
dyld: Library not loaded: @rpath/libswiftCore.dylib
  Referenced from: /private/var/containers/Bundle/Application/572835B3-D250-4C6A-AD14-4CF8F559C6D6/neon.app/Frameworks/IDNowSDKCore.framework/IDNowSDKCore
  Reason: image not found
```

Versions our customers had when reporting the issue:
iOS 10:
10.3.4

iOS 11:
11.0.0, 11.3.1, 11.4.0, 11.4.1

iOS 12:
iOS 12.1.0-12.1.4

We are building our app with xcode 11.3.

When the customers upgrade to iOS 13 it works but we need to be able to support at least all versions of iOS 12

**Comment by BilelSelmiIDnow** [comment]
@timohe : Can you please confirm if you followed this in documentation: go to Pods, then under Targets look for Alamofire, OpenCV2, Sentry and Starscream, under Build Settings set Build Libraries for Distribution for the pods to Yes, Otherwise you’ll get dyld: Symbol not found error at runtime.
Can you also please also

**Comment by BilelSelmiIDnow** [comment]
@timohe : Can you please confirm if you followed this in documentation: go to Pods, then under Targets look for Alamofire, OpenCV2, Sentry and Starscream, under Build Settings set Build Libraries for Distribution for the pods to Yes, Otherwise you’ll get dyld: Symbol not found error at runtime.

**Comment by ChernyshenkoTaras** [comment]
@BilelSelmiIDnow hi! We are using `Carthage` for installing those libraries and followed all steps to add `Run Script Phase`, so it can't be an issue

**Comment by BilelSelmiIDnow** [comment]
@timohe

**Comment by BilelSelmiIDnow** [comment]
@ChernyshenkoTaras : Can you please confirm that this issue dyld: Library not loaded:, is only seen on iOS versions lower than iOS 13 . Thanks.

**Comment by BilelSelmiIDnow** [comment]
@ChernyshenkoTaras : Can you please confirm that this issue dyld: Library not loaded:, is only seen on iOS versions lower than iOS 13 . Thanks.

**Comment by ChernyshenkoTaras** [comment]
@BilelSelmiIDnow yes, this issue is not reproducible on iOS 13+, also I was not able to reproduce it using iOS 12.4.

We did reproduce it with iOS 10.3.2, also our clients are reporting the same issue with 11.0.0, 11.3.1, 11.4.0, 11.4.1 and 12.1.0-12.1.4

**Comment by BilelSelmiIDnow** [comment]
@ChernyshenkoTaras : thanks for the info.
We will look into this issue.

**Comment by BilelSelmiIDnow** [comment]
@ChernyshenkoTaras  
I tried with iOS 10.3.3 and couldn't reproduce the issue, please make sure to embed and sign the following frameworks for version 3.21.0 
 IDNowSDKCore.framework 
 Alamofire.framework
 Sentry.framework
 Starscream.framework

And if you already on version 3.22.0 : please do the same for the following frameworks : 
 IDNowSDKCore.framework 
  Alamofire.framework
  Sentry.framework
  Starscream.framework
  ZoomAuthentication.framework.

Please let us know if you are still able to reproduce issue with lower iOS versions

**Comment by ChernyshenkoTaras** [comment]
@BilelSelmiIDnow here is a sample project what reproduce that issue https://github.com/ChernyshenkoTaras/IDNow-crash-reproduce
When I trying to run this project with 10.3.2 iOS it constantly crashes for me.

**Comment by BilelSelmiIDnow** [comment]
@ChernyshenkoTaras : I tried to reproduce the issue using iOS 10.3.3 in a Swift project but it is not reproducible.
I tried to reproduce the issue using your sample project and it worked fine with iOS 13.
But when I tried with iOS 10.3.3 in your Objective-C sample app, I reproduced the issue.
In order to fix the issue, please go to Build Settings and look for Always Embed Swift Standard Libraries and set it to Yes.

**Comment by ChernyshenkoTaras** [comment]
@BilelSelmiIDnow it works. Thanks a lot for your help!

**Comment by BilelSelmiIDnow** [comment]
@ChernyshenkoTaras : You are very welcome.
