### ISSUE TITLE
Set phone number

### ISSUE THREAD

**Issue by IvanFomenkoAndersenLab** [idnow/de.idnow.ios.sdk#18]
In Android we can use
![picturemessage_crm4flmk 0fl](https://user-images.githubusercontent.com/64132053/86742113-8cbf2b00-c040-11ea-99ce-701210647b60.png)
Do you the same property for setting user phone number in iOS?

**Comment by BilelSelmiIDnow** [comment]
Hi @IvanFomenkoAndersenLab, this is Android video Ident SDK, please refer to Video Ident on GitHub. 
https://github.com/idnow/de.idnow.android
https://github.com/idnow/de.idnow.ios
