### ISSUE TITLE
App crashes

### ISSUE THREAD

**Issue by Galiza** [idnow/de.idnow.ios.sdk#19]
We tried updating to the latest version (3.22.0), but when running our app, it now crashes, previous to the latest version, we were using the _IDNowSDKCore-Xcode_11.3.1.json_, but we noticed that there's no update on this one, so we tried pointing to the _IDNow-iOS-11.3.json_, which is the one with the actual changes but it crashed.

This is our new carthage file:
```
binary "https://raw.githubusercontent.com/idnow/de.idnow.ios.sdk/master/IDNow-iOS-11.3.json"
binary "https://raw.githubusercontent.com/idnow/de.idnow.ios.sdk/master/OpenCV2.json"
github "Alamofire/Alamofire" "4.8.2"
github "getsentry/sentry-cocoa" "4.1.0"
github "daltoniam/Starscream"  "3.1.0"
```

This was the old carthage file:
```
binary "https://raw.githubusercontent.com/idnow/de.idnow.ios.sdk/master/IDNowSDKCore-Xcode_11.3.1.json"
binary "https://raw.githubusercontent.com/idnow/de.idnow.ios.sdk/master/OpenCV2.json"
github "Alamofire/Alamofire" "4.8.2"
github "getsentry/sentry-cocoa" "4.1.0"
github "daltoniam/Starscream"  "3.1.0"
```

How should we proceed?

**Comment by thuleidnow** [comment]
hi @Galiza ,

we are investigating and let you soon after we found out something.

Best regards

**Comment by BilelSelmiIDnow** [comment]
@Galiza : Hi we added a new liveness technology so our SDK 3.22.0 is dependent on it please use the following cartfile : 

`binary "https://raw.githubusercontent.com/idnow/de.idnow.ios.sdk/master/IDNow-iOS-11.3.json"
binary "https://downloads.idnow.de/ios/ZoomAuthentication.json"
binary "https://raw.githubusercontent.com/idnow/de.idnow.ios.sdk/master/OpenCV2.json"
github "Alamofire/Alamofire" "4.8.2"
github "getsentry/sentry-cocoa" "4.1.0"
github "daltoniam/Starscream"  "3.1.0"`

**Comment by Galiza** [comment]
@BilelSelmiIDnow @thuleidnow I've added this binary on the cartfile, but the crash still happens.

Our XCode version is: 11.3.1 and prior to this last update, it used to work without any issues whatsoever.

**Comment by BilelSelmiIDnow** [comment]
@Galiza : Can you please create a sample project that reproduces the issue?
This will be very helpful to investigate and fix the issue.

Thanks in advance.

**Comment by timohe** [comment]
I uploaded a version of our app here (build 7262). you can install it directly on ios from this page and you should be able to reproduce it and debug it https://install.appcenter.ms/orgs/neonbanking/apps/neon-intrum-dev-ios/distribution_groups/public%20for%20idnow%2fintrum

If you still need a sample project, let us know

**Comment by BilelSelmiIDnow** [comment]
@timohe : Thanks for uploading the version that Crashes. 
It would be helpful from your side, if you can create a sample project then we can debug it. Thanks in advance.

**Comment by BilelSelmiIDnow** [comment]
I had a look at the iPhone crash logs for neon app and it seems that ZoomAuthentication.framework not loaded.
Please add the framework to the General->Frameworks, Libraries And Embedded Content section in the General tab of your app target.
Make sure you select the 'Embed & Sign' option.
