### ISSUE TITLE
Latest version is not usable from Objective-C 

### ISSUE THREAD

**Issue by semdangelo** [idnow/de.idnow.ios.sdk#21]
Hello,  
updating to version 4.3.0 from 3.23.0 we have now a compilation error where we are using your product:
 
`IDNowSDK.shared` ==> Property 'shared' not found on object of type 'IDNowSDK'

Inspecting your Demo project we discovered that the same attribute is invokable through swift, and that it is not exposed to Objective-C classes as opposed to the previous version.

**Comment by BilelSelmiIDnow** [comment]
@semdangelo : This is fixed in 4.6.0
