### ISSUE TITLE
version 4.3.0 crashes on app launch

### ISSUE THREAD

**Issue by semdangelo** [idnow/de.idnow.ios.sdk#22]
Hello,  

we receive the following error on app launch:

```
dyld: Library not loaded: @rpath/Sentry.framework/Sentry
  Referenced from: /private/var/containers/Bundle/Application/<redacted>/<redacted>.app/Frameworks/IDNowSDKCore.framework/IDNowSDKCore
  Reason: image not found
dyld: launch, loading dependent libraries
DYLD_LIBRARY_PATH=/usr/lib/system/introspection
DYLD_INSERT_LIBRARIES=/Developer/usr/lib/libBacktraceRecording.dylib:/Developer/Library/PrivateFrameworks/GPUTools.framework/libglInterpose.dylib:/usr/lib/libMTLCapture.dylib:/Developer/Library/PrivateFrameworks/DTDDISupport.framework/libViewDebuggerSupport.dylib
```

After that, the system terminates the application.
You can reproduce the problem with Xcode 12.0.1 with the Demo project included in the 4.3.0 release.

**Comment by BilelSelmiIDnow** [comment]
@semdangelo : Thanks for reporting the issue.
 Could you please. Provide a demo project reproducing the issue using IDNowSDKCore.framework in : 
https://github.com/idnow/de.idnow.ios.sdk/tree/IDNowSDK/IDnow-platform-iOS-4.3.0

**Comment by BilelSelmiIDnow** [comment]
@semdangelo : Please try with latest release

**Comment by yoannHertienne** [comment]
Hello,
 
 I'm also having the same issue with XCode 12.4 (12D4e) on iOS 14.4, with React-Native 0.64 and AutoIdent SDK 4.7.4:

**dyld: Library not loaded: @rpath/Sentry.framework/Sentry
  Referenced from: /Users/yoann.hertienne/Library/Developer/CoreSimulator/Devices/769F83B2-5F09-4EE8-B8A0-71036BBCD23D/data/Containers/Bundle/Application/57B339D0-10AB-420F-A5D9-753D4CAD688F/AutoIdentPOC.app/Frameworks/IDNowSDKCore.framework/IDNowSDKCore
  Reason: image not found**
