### ISSUE TITLE
color customization

### ISSUE THREAD

**Issue by Waseem-Coeus** [idnow/de.idnow.ios.sdk#24]
Hi, I want to customize the appearance (Colors mainly) to match my parent app. So far I have only found it for videoIdent. Can you guide me towards right direction to customize autoIdent.

VideoIdent customization:
https://github.com/idnow/de.idnow.ios#colors

**Comment by thuleidnow** [comment]
hi @Waseem-Coeus ,

You could not customize the color as in videoident via sdk.

But you can do it for Autoident by customizing the color from our server side. Each customer we define a configurable file from back-end side. plz contact our customer support team to help you define a configuration in this case?

cc: @BilelSelmiIDnow , @sleski , @souheib93 

Regards,
Thu
