### ISSUE TITLE
Could not find module 'IDNowSDKCore' for target 'x86_64-apple-ios-simulator'

### ISSUE THREAD

**Issue by billidani7** [idnow/de.idnow.ios.sdk#27]
Hi,

After installing your SDK, I can't run my app on simulator. How can I solve this error:
`Could not find module 'IDNowSDKCore' for target 'x86_64-apple-ios-simulator'; found: arm64, armv7-apple-ios, arm64-apple-ios, arm, armv7`

Xcode 12.4

Thanks

**Comment by BilelSelmiIDnow** [comment]
@billidani7 : I assume you were using CocoaPods as a dependency manager, and you downloaded the SDK from
https://github.com/idnow/de.idnow.ios.sdk/tree/master/IDnow-platform-iOS-4.7.0.
The Framework only contains device architectures, If you need the simulator architectures as well. Please contact IDnow customer support.

Kind regards,
Bilel
