### ISSUE TITLE
Prefix your dependencies

### ISSUE THREAD

**Issue by AndreasVerhoeven** [idnow/de.idnow.ios.sdk#28]
The IDNow frameworks seems to contain a few 3rd party dependencies, without prefixing their names. This causes name clashes.

It's common practice for frameworks to prefix **all** used names (classes, categories) that can clash. In this case, we have a conflicting dependency with `NBPhoneNumber`. 

**PLEASE PREFIX YOUR THIRD PARTY DEPENDENCIES**

**Comment by BilelSelmiIDnow** [comment]
@AndreasVerhoeven : This issue has to do with Video Ident iOS SDK Please reach out to VideoIdent team for support : https://github.com/idnow/de.idnow.ios
