### ISSUE TITLE
Carthage problems

### ISSUE THREAD

**Issue by GuillermoCiqueHolvi** [idnow/de.idnow.ios.sdk#3]
There are differences between the framework in the repository and the one in the releases section:

**Repository:**
 - Does not work in simulator
 - Does not embed dependencies
 - Framework is in the root of the ZIP file

**Releases section:**
 - Works in simulator
 - Embeds dependencies
 - Framework is buried in a Carthage/Build/iOS folder

It is also unclear the full set of dependencies, the Carthage dependencies listed in the README.md are missing: AlamofireLogger, OpenCV2 and SwiftMsgPack.
These dependencies seem to not be required when using the framework in the Releases section but are necessary when using the one in the repository.

Right now we are still unable to use Carthage to manage this framework, we are still forced to download manually both frameworks double checking if the frameworks are still different. We are using the one in the releases section but we are removing the Frameworks embedded as to not have repeated frameworks.

**This is what we need:**
 - Works in simulator
 - Does not embed dependencies
 - Framework is in the root of the ZIP file

**Comment by BilelSelmiIDnow** [comment]
Thanks for your Contribution, the current release 3.17.0 : 

- Works in simulator
- Does not embed dependencies
- Framework is in the root of the ZIP file
