### ISSUE TITLE
Malformed swiftmodule

### ISSUE THREAD

**Issue by gyulavoros** [idnow/de.idnow.ios.sdk#36]
While compiling our project, we experience the following error emitted by Xcode:

```
Carthage/Build/iOS/IDNowSDKCore.framework/Modules/IDNowSDKCore.swiftmodule/Project/arm64-apple-ios.swiftsourceinfo' is either malformed or generated by a different Swift version. Note that it uses an unstable format and may leak internal project details, it should not be distributed alongside modules
```

Our project setup:
- We use Carthage and IDNow SDK version `4.12.0`
- We are on Xcode `13.1.0 (13A1030d)`

**Comment by gyulavoros** [comment]
Do you have any updates on this? It still affects version `4.13.0` with the latest Xcode (`13.2.1 `).

**Comment by michael-eckl-idnow** [comment]
Hi @gyulavoros ,

we released a newer version of the SDK 4.15.0 (xcframeworks).
Please checkout here: https://github.com/idnow/de.idnow.ios.sdk.spm.

If there are further actions needed please reach out to your Customer Success.

Best regards,
Michael

Note: This repository will not contain further SDK Updates

**Comment by gyulavoros** [comment]
@michael-eckl-idnow the XCFramework support sounds great! Does the new repository support Carthage as well?

**Comment by BilelSelmiIDnow** [comment]
@gyulavoros : we are not supporting Carthage anymore.
