### ISSUE TITLE
Support for SPM

### ISSUE THREAD

**Issue by emadhegab** [idnow/de.idnow.ios.sdk#39]
Will there be any support soon for SPM ?

**Comment by michael-eckl-idnow** [comment]
Hi @emadhegab ,

please see: https://github.com/idnow/de.idnow.ios.sdk.spm

**Comment by emadhegab** [comment]
thanks

**Comment by emadhegab** [comment]
@michael-eckl-idnow  turn out that this spm package doesn't have video Identifier . 
do you know if there's one?
