### ISSUE TITLE
Found an unexpected Mach-O header error when archive

### ISSUE THREAD

**Issue by ChernyshenkoTaras** [idnow/de.idnow.ios.sdk#5]
### Abstract
When I archive project and try to distribute it I get `Found an unexpected Mach-O header` error message. I will really appreciate if somebody will help me to resolve this issue.

### Details
I added `IDnow framework` thru carthage as described in `Installation` instruction.

When I make build or even run app on device everything is working. However when I want to distribute app I get  `Found an unexpected Mach-O header` error

![2020-01-10_14-26-01](https://user-images.githubusercontent.com/9074648/72153562-038faa00-33b7-11ea-9b6a-3046784ade6e.png)

Logs:

`2020-01-10 12:50:27 +0000  Failed to generate distribution items with error: Error Domain=DVTMachOErrorDomain Code=0 "Found an unexpected Mach-O header code: 0x72613c21" UserInfo={NSLocalizedDescription=Found an unexpected Mach-O header code: 0x72613c21, NSLocalizedRecoverySuggestion=}`

I made small project what reproduce this issue: https://github.com/ChernyshenkoTaras/IDNowTest

Environment:
```
Xcode: 10.2
Carthage: 0.34.0
```

**Steps to reproduce:**
1. Load project from https://github.com/ChernyshenkoTaras/IDNowTest
2. Open project root folder and run `carthage update --platform iOS`
3. Change TeamID to your own
4. Archive project
5. Distribute it with `Development` method

**Actual result:** Found an unexpected Mach-O header error appear
**Expected result** It should be possible to distribute app

**Comment by BilelSelmiIDnow** [comment]
Hi @ChernyshenkoTaras : thanks for reporting this issue, The problem is solved for the current release 3.17.0, please follow the current documentation.
